// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQw25IIfDSGpS5QEnaF2hLg3khHHhmUAc',
    appId: '1:1096815867027:web:dd910434c2b2a0b8a80966',
    messagingSenderId: '1096815867027',
    projectId: 'products-c894f',
    authDomain: 'products-c894f.firebaseapp.com',
    storageBucket: 'products-c894f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfMYxaMyK79s_Zi3Fj_earSEsdUQmLis',
    appId: '1:1096815867027:android:50b12ce6d1519c4da80966',
    messagingSenderId: '1096815867027',
    projectId: 'products-c894f',
    storageBucket: 'products-c894f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-9RXlPb-ZTdr6pmpTlct8UuCMAyGCvio',
    appId: '1:1096815867027:ios:3dfa7f82218baa05a80966',
    messagingSenderId: '1096815867027',
    projectId: 'products-c894f',
    storageBucket: 'products-c894f.appspot.com',
    iosClientId: '1096815867027-5duvedhcs8i2a6ca0r5pn3404udbab4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.productsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-9RXlPb-ZTdr6pmpTlct8UuCMAyGCvio',
    appId: '1:1096815867027:ios:3dfa7f82218baa05a80966',
    messagingSenderId: '1096815867027',
    projectId: 'products-c894f',
    storageBucket: 'products-c894f.appspot.com',
    iosClientId: '1096815867027-5duvedhcs8i2a6ca0r5pn3404udbab4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.productsApp',
  );
}
